### ISSUE TITLE
extra-pane panel rendering html as Latin-1 instead of utf-8

### ISSUE THREAD

**Issue by ansaso** [mr-pennyworth/alfred-extra-pane#1]
When writing unicode characters (>255) like `å` or `ñ` the extra pane appears to render them as Latin-1 instead of utf-8. 

for instance the alfred script:
`echo '{"items":[{"title":"test", "quicklookurl":"~/test.html"}]}'|/Applications/AlfredExtraPane.app/Contents/Resources/scripts/alfred-extra-pane`

where `~/test.html` is:
```
<html>
  <body>
    <h1>
      å
    </h1>
  </body>
</html>
```
results in the extrapane panel: 

<img width="862" alt="alfred-extrapane-incorrect" src="https://user-images.githubusercontent.com/61746722/103238553-5d341000-494b-11eb-89d6-6ca2ea93bfa5.png">

however the alfred quickview renders it correctly as:

<img width="368" alt="alfred-quickview-correct" src="https://user-images.githubusercontent.com/61746722/103238573-6b822c00-494b-11eb-9d3a-27038fbbc314.png">

**Comment by mr-pennyworth** [comment]
The extra pane uses [WkWebView](https://developer.apple.com/documentation/webkit/wkwebview), which is based on Safari. This is what happens if I open `test.html` in Safari:
<img width="686" alt="safari" src="https://user-images.githubusercontent.com/74945464/103259521-bd649980-49bf-11eb-8aa9-f6731c4202e6.png">

Adding `charset` meta tag to html fixes it:
```html
<html>
  <head>
    <meta charset="UTF-8">
  </head>
  <body>
    <h1>
      å
    </h1>
  </body>
</html>
```
