### ISSUE TITLE
Prompt wants access to `WebCrypto Master Key`

### ISSUE THREAD

**Issue by chrisgrieser** [mr-pennyworth/alfred-extra-pane#18]
Not sure what happened here – I use various workflows that previews URLs, and occasionally this started showing up. What is this about?

![Pasted image 2024-07-30 at 14 24 33@2x](https://github.com/user-attachments/assets/3cc8254e-b94f-4f66-b1de-1b318f219f0c)

**Comment by mr-pennyworth** [comment]
Thanks for reporting @chrisgrieser!
Seems like something to do with websites that stream DRM-protected videos? (like Netflix)
https://forums.macrumors.com/threads/webcrypto-master-key.2387693/

I can look further into it if you could help me with the specific website for which this happens.
I tried it with https://www.netflix.com, but it seems to work all right...

another related issue I see: https://github.com/xamarin/xamarin-macios/issues/14167

**Comment by chrisgrieser** [comment]
Two URLs I am getting the issue at are these:
- https://www.theverge.com/24067997/robots-txt-ai-text-file-web-crawlers-spiders
- https://www.economist.com/finance-and-economics/2023/07/16/your-employer-is-probably-unprepared-for-artificial-intelligence

both do not contain any videos (aside from ads)?

**Comment by glowacky** [comment]
@chrisgrieser The common thread between those two links appears to be [parsely.com](https://www.parse.ly/), which could be related to content protection that triggers [WebKit's Web Crypto features](https://webkit.org/blog/7790/update-on-web-cryptography/).

Maybe try accessing a URL on another site that uses Parse.ly to see if the same message appears. For instance, here's a random link from NBC News: https://www.nbcnews.com/sports/olympics/are-different-olympic-medal-counts-know-tally-rcna164477

**Comment by chrisgrieser** [comment]
@glowacky With that nbc link, I do not get any issues

**Comment by mr-pennyworth** [comment]
@chrisgrieser since it is asking access to its own key, there's no harm in providing access.
It should be a one-time thing. My guess is that the `AlfredExtraPane` that created the key is
different from the one which is accessing it. (Likely because it was updated?)

Looking at the discussion here https://forums.macrumors.com/threads/webcrypto-master-key.2387693/
Another way would be to just delete the key using `Keychain Access` app
<img width="1085" alt="image" src="https://github.com/user-attachments/assets/4378e155-0a5d-4e98-96ed-85a30c4eefd2">

Once deleted, later, I'm assuming, the app will create the key whenever it is needed.

If neither of the above solve the issue, feel free to re-open the issue :)
