### ISSUE TITLE
Adjust Pane Width

### ISSUE THREAD

**Issue by chrisgrieser** [mr-pennyworth/alfred-extra-pane#6]
The extra pane is rather squished to the side for me, being able to adjust the width would be quite useful

![Pasted image 2024-02-23 at 17 16 25@2x](https://github.com/mr-pennyworth/alfred-better-dictionaries/assets/73286100/e8966cc4-594e-44b7-8e15-f8e3ce64293d)

**Comment by mr-pennyworth** [comment]
That's a cool idea @chrisgrieser!
I've updated `AlfredExtraPane` so that now the appearance of the pane(s) can be configured by editing
`~/Library/Application Support/mr.pennyworth.AlfredExtraPane/config.json`

Here's an example with four panes configured:
```json
[{
  "workflowUID" : "*",
  "alignment" : {
    "horizontal" : {"placement" : "right", "width" : 300, "minHeight" : 400}}
}, {
  "workflowUID" : "*",
  "alignment" : {
    "horizontal" : {"placement" : "left", "width" : 300, "minHeight" : 400}}
}, {
  "workflowUID" : "*",
  "alignment" : {
    "vertical" : {"placement" : "top", "height" : 100}}
}, {
  "workflowUID" : "*",
  "alignment" : {
    "vertical" : {"placement" : "bottom", "height" : 200}}
}]
```

<img width="1361" alt="image" src="https://github.com/mr-pennyworth/alfred-extra-pane/assets/74945464/94814c4f-166f-4d0b-86c0-bcb0fea3432a">
